GET http://localhost:5154/times

###

GET http://localhost:5154/times/4

###

PUT http://localhost:5154/times/3
Content-Type: application/json

{
    "nome" : "Real Madrid",
    "cidade" : "Madrid",
    "titulosbrasileiros" : 0,
    "titulosmundiais" : 8
}

###

GET http://localhost:5154/jogadores